image:
  repository: npplstatecr.azurecr.io/dc-janitor
  tag: 8dcf067
  pullPolicy: IfNotPresent
kubejanitor:
cron:
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 5
restartPolicy: OnFailure
resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 5m
    memory: 100Mi
